[package]
name = "seer"
version = "0.1.0"
edition = "2024"

[features]
default = []
cuda = ["candle-core/cuda", "candle-nn/cuda"]
metal = ["candle-core/metal", "candle-nn/metal"]

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle" }
candle-nn   = { git = "https://github.com/huggingface/candle" }
tokenizers = "0.23.1"
rand = "0.8"
